-- mux_relojes.vhd

-- Generated using ACDS version 18.1 625

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mux_relojes is
	port (
		inclk2x   : in  std_logic                    := '0';             --  altclkctrl_input.inclk2x
		inclk1x   : in  std_logic                    := '0';             --                  .inclk1x
		inclk0x   : in  std_logic                    := '0';             --                  .inclk0x
		clkselect : in  std_logic_vector(1 downto 0) := (others => '0'); --                  .clkselect
		outclk    : out std_logic                                        -- altclkctrl_output.outclk
	);
end entity mux_relojes;

architecture rtl of mux_relojes is
	component mux_relojes_altclkctrl_0 is
		port (
			inclk2x   : in  std_logic                    := 'X';             -- inclk2x
			inclk1x   : in  std_logic                    := 'X';             -- inclk1x
			inclk0x   : in  std_logic                    := 'X';             -- inclk0x
			clkselect : in  std_logic_vector(1 downto 0) := (others => 'X'); -- clkselect
			outclk    : out std_logic                                        -- outclk
		);
	end component mux_relojes_altclkctrl_0;

begin

	altclkctrl_0 : component mux_relojes_altclkctrl_0
		port map (
			inclk2x   => inclk2x,   --  altclkctrl_input.inclk2x
			inclk1x   => inclk1x,   --                  .inclk1x
			inclk0x   => inclk0x,   --                  .inclk0x
			clkselect => clkselect, --                  .clkselect
			outclk    => outclk     -- altclkctrl_output.outclk
		);

end architecture rtl; -- of mux_relojes
